Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "debian/jessie64"

#        web.vm.network :forwarded_port, guest: 8080, host: 28080
    web.vm.network "private_network", ip: "192.168.9.21"

      # web.vm.provision "shell", path: "bootstrap-web.sh"
      # web.vm.provision "shell", path: "deploy.sh"
  end

  config.vm.define "db" do |db|
    db.vm.box = "debian/jessie64"

    # db.vm.network :forwarded_port, guest: 27017, host: 2217
    db.vm.network "private_network", ip: "192.168.9.22"

    # db.vm.provision "shell", path: "bootstrap-db.sh"
  end
end
